version: '3'
services:
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.6
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - TOPOSOID_JVM_XMS=512m
      - TOPOSOID_JVM_XMX=1g
      - TOPOSOID_JVM_XSS=512k
      - PLAY_HTTP_PORT=9001
    ports:
      - 9001:9001
