version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-sentence-parser-web:
    image: toposoid/toposoid-sentence-parser-web:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.3
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9001:9001




