version: '3'
services:
  toposoid-sentence-parser-japanese-web:
    image: toposoid-sentence-parser-japanese-web:0.6-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sentence-parser-japanese-web
      - TOPOSOID_JVM_XMS=512m
      - TOPOSOID_JVM_XMX=1g
      - TOPOSOID_JVM_XSS=512k
      - PLAY_HTTP_PORT=9001
