version: '3'
services:
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.2
