version: '3'
services:
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.5-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9001
    ports:
      - 9001:9001
